export { createAttributeFormConfig } from './attributeFormConfig'
export { createLoginFormConfig, createRegisterFormConfig } from './authFormConfig'
export { createPositionInfoFormConfig, createPositionRelationsFormConfig } from './positionFormConfig'
export { createProjectFormConfig } from './projectFormConfig'
export { createResumeFormConfig } from './resumeFormConfig'
export { createTagFormConfig } from './tagFormConfig'
export { createChangeRoleFormConfig, createUserFormConfig } from './userFormConfig'
